import express from "express";
import crypto from "node:crypto";

const app=express();
const ALLOWED_ORIGIN="https://yashraj-ghemud.github.io";
app.use((req,res,next)=>{const origin=req.headers.origin;if(origin===ALLOWED_ORIGIN)res.setHeader("Access-Control-Allow-Origin",origin);res.setHeader("Vary","Origin");res.setHeader("Access-Control-Allow-Methods","GET,POST,OPTIONS");res.setHeader("Access-Control-Allow-Headers","Content-Type,x-api-key");if(req.method==="OPTIONS")return res.sendStatus(204);next()});
app.use(express.json({limit:"20kb"}));
const OWNER=process.env.GITHUB_OWNER;const REPO=process.env.GITHUB_REPO;const PAT=process.env.GITHUB_PAT;const BRANCH=process.env.GITHUB_BRANCH||"main";const JOBS_PATH=process.env.JOBS_PATH||"data/jobs.json";const API_KEY=process.env.SCHEDULER_API_KEY||"";
function assertConfig(){if(!OWNER||!REPO||!PAT)throw new Error("Missing GITHUB_OWNER, GITHUB_REPO or GITHUB_PAT")}
function validMeetingUrl(value){try{const u=new URL(value);return u.protocol==="https:"&&(u.hostname==="teams.microsoft.com"||u.hostname.endsWith(".teams.microsoft.com")||u.hostname==="zoom.us"||u.hostname.endsWith(".zoom.us"))}catch{return false}}
function requireKey(req,res){if(API_KEY&&req.get("x-api-key")!==API_KEY){res.status(401).json({error:"Unauthorized"});return false}return true}
async function github(path,options={}){assertConfig();const r=await fetch(`https://api.github.com/repos/${OWNER}/${REPO}/contents/${path}`,{...options,headers:{Accept:"application/vnd.github+json",Authorization:`Bearer ${PAT}`,"X-GitHub-Api-Version":"2022-11-28",...(options.headers||{})}});const text=await r.text();let body;try{body=JSON.parse(text)}catch{body={message:text}}if(!r.ok)throw new Error(body.message||`GitHub API ${r.status}`);return body}
async function readJobs(){try{const file=await github(JOBS_PATH);return{jobs:JSON.parse(Buffer.from(file.content,"base64").toString("utf8")),sha:file.sha}}catch(e){if(String(e.message).includes("Not Found"))return{jobs:[],sha:null};throw e}}
async function writeJobs(jobs,sha){const content=Buffer.from(JSON.stringify(jobs,null,2)+"\n").toString("base64");return github(JOBS_PATH,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:"chore: update meeting jobs",content,branch:BRANCH,...(sha?{sha}:{})})})}
async function dispatch(job){return github("actions/workflows/join-meeting.yml/dispatches",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ref:BRANCH,inputs:{meeting_link:job.meetingLink,display_name:job.displayName,start_time:job.startTime,duration_minutes:String(job.durationMinutes),job_id:job.id}})})}
app.get("/api/health",(req,res)=>res.json({ok:true}));
app.get("/api/meetings",async(req,res)=>{try{if(!requireKey(req,res))return;const{jobs}=await readJobs();res.json({meetings:jobs.sort((a,b)=>new Date(a.startTime)-new Date(b.startTime))})}catch(e){res.status(500).json({error:e.message})}});
app.post("/api/schedule-meeting",async(req,res)=>{try{if(!requireKey(req,res))return;const{meetingLink,displayName,startTime,endTime}=req.body||{};if(!validMeetingUrl(meetingLink))return res.status(400).json({error:"Only valid HTTPS Teams/Zoom meeting URLs are accepted."});if(typeof displayName!=="string"||!displayName.trim()||displayName.length>80)return res.status(400).json({error:"displayName must be 1–80 characters."});const start=Date.parse(startTime),end=Date.parse(endTime);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)return res.status(400).json({error:"endTime must be later than startTime."});const durationMinutes=Math.ceil((end-start)/60000);const{jobs,sha}=await readJobs();const job={id:crypto.randomUUID(),meetingLink,displayName:displayName.trim(),startTime:new Date(start).toISOString(),endTime:new Date(end).toISOString(),durationMinutes,status:"pending",createdAt:new Date().toISOString()};jobs.push(job);await writeJobs(jobs,sha);await dispatch(job);res.status(201).json({status:"scheduled",meeting:job})}catch(e){console.error(e);res.status(500).json({error:e.message})}});
export default app;
